# .github/workflows/ci.yml

name: Node.js CI

# Déclencheurs du workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # L'environnement sur lequel le job va tourner
    runs-on: ubuntu-latest

    strategy:
      # Tester sur plusieurs versions de Node.js pour assurer la compatibilité
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    # Étape 1: Récupérer le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2: Configurer Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Mettre en cache les dépendances pour accélérer les builds

    # Étape 3: Installer les dépendances
    - name: Install dependencies
      run: npm ci

    # Étape 4: Lancer les tests
    - name: Run tests
      run: npm test 